apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: github
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitHub
  description: GitHub Inc. is an Internet hosting service for software development and version control using Git.
  logo: /plugins/plugin-oauth2/assets/static/github.svg
  website: https://github.com
  helpPage: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  authenticationUrl: /oauth2/authorization/github
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/github
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/github
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-github-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitee
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Gitee
  description: Gitee is an online forge that allows software version control using Git and is intended primarily for the hosting of open source software.
  logo: /plugins/plugin-oauth2/assets/static/gitee.svg
  website: https://gitee.com
  authenticationUrl: /oauth2/authorization/gitee
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/gitee
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/gitee
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitee-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitlab
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitLab
  description: GitLab Inc. is an open-core company that operates GitLab, a DevOps software package which can develop, secure, and operate software.
  logo: /plugins/plugin-oauth2/assets/static/gitlab.svg
  website: https://gitlab.com
  authenticationUrl: /oauth2/authorization/gitlab
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/gitlab
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/gitlab
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitlab-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: logto
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Logto
  description: Logto is an Auth0 alternative designed for modern apps and SaaS products. It offers a seamless developer experience and is well-suited for individuals and growing companies.
  logo: /plugins/plugin-oauth2/assets/static/logto.svg
  website: https://logto.io
  authenticationUrl: /oauth2/authorization/logto
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/logto
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/logto
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-logto-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: authing
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Authing
  description: Authing quickly implements authentication and user management for any Web, App, and enterprise software to provide the most complete login solution for your customers and employees.
  logo: /plugins/plugin-oauth2/assets/static/authing.svg
  website: https://www.authing.cn
  authenticationUrl: /oauth2/authorization/authing
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/authing
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/authing
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-authing-config
