apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: github
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/github"
  scopes:
    - "read:user"
  authorizationUri: "https://github.com/login/oauth/authorize"
  tokenUri: "https://github.com/login/oauth/access_token"
  userInfoUri: "https://api.github.com/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "id"
  clientName: "GitHub"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitee
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitee"
  scopes:
    - "user_info"
  authorizationUri: "https://gitee.com/oauth/authorize"
  tokenUri: "https://gitee.com/oauth/token"
  userInfoUri: "https://gitee.com/api/v5/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "login"
  clientName: "Gitee"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitlab
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitlab"
  scopes:
    - "read_user"
  authorizationUri: "https://gitlab.com/oauth/authorize"
  tokenUri: "https://gitlab.com/oauth/token"
  userInfoUri: "https://gitlab.com/api/v4/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "GitLab"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: logto
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/logto"
  scopes:
    - "openid"
    - "profile"
    - "email"
  authorizationUri: "https://sso.a2008q.top/oidc/auth"
  tokenUri: "https://sso.a2008q.top/oidc/token"
  userInfoUri: "https://sso.a2008q.top/oidc/me"
  jwkSetUri: "https://sso.a2008q.top/oidc/jwks"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "Logto"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: authing
spec:
  clientAuthenticationMethod: "client_secret_post"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/authing"
  scopes:
    - "openid"
    - "username"
  authorizationUri: "https://seeyonoa.authing.cn/oidc/auth"
  tokenUri: "https://seeyonoa.authing.cn/oidc/token"
  userInfoUri: "https://seeyonoa.authing.cn/oidc/me"
  jwkSetUri: "https://seeyonoa.authing.cn/oidc/.well-known/jwks.json"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "Authing"
